settings:
  min_record_length: 10
  strict_mode: false
  encoding: latin1

schemas:
  '01':
    name: DAROOT
    expected_min_length: 510
    storage_key: null
    fields:
      - name: rrc_tape_record_id
        start: 1
        end: 3
        type: str
      - name: status_number
        start: 3
        end: 10
        type: str
      - name: status_sequence_number
        start: 10
        end: 12
        type: str
      - name: county_code
        start: 12
        end: 15
        type: str
        validator: county_code
      - name: lease_name
        start: 15
        end: 47
        type: str
        required: true
      - name: district
        start: 47
        end: 49
        type: str
        validator: district
      - name: operator_number
        start: 49
        end: 55
        type: str
        validator: operator_number
      - name: operator_name
        start: 67
        end: 99
        type: str
      - name: permit_number
        start: 113
        end: 120
        type: str
        required: true

  '02':
    name: DAPERMIT
    expected_min_length: 510
    storage_key: null
    fields:
      - name: rrc_tape_record_id
        start: 1
        end: 3
        type: str
      - name: permit_number
        start: 5
        end: 12
        type: str
        required: true
      - name: county_code
        start: 14
        end: 17
        type: str
        validator: county_code
      - name: lease_name
        start: 17
        end: 49
        type: str
      - name: district
        start: 49
        end: 51
        type: str
      - name: well_number
        start: 51
        end: 57
        type: str
      - name: total_depth
        start: 57
        end: 62
        type: int
      - name: operator_number
        start: 62
        end: 68
        type: str
      - name: well_status
        start: 171
        end: 172
        type: str
      - name: directional_flag
        start: 483
        end: 484
        type: str
      - name: sidetrack_flag
        start: 484
        end: 485
        type: str
      - name: horizontal_flag
        start: 495
        end: 496
        type: str

  '14':
    name: GIS_SURFACE
    expected_min_length: 26
    storage_key: gis_surface
    fields:
      - name: rrc_tape_record_id
        start: 1
        end: 3
        type: str
      - name: longitude
        start: 3
        end: 15
        type: float
        validator: longitude
      - name: latitude
        start: 15
        end: 27
        type: float
        validator: latitude

  '15':
    name: GIS_BOTTOMHOLE
    expected_min_length: 26
    storage_key: gis_bottomhole
    fields:
      - name: rrc_tape_record_id
        start: 1
        end: 3
        type: str
      - name: longitude
        start: 3
        end: 15
        type: float
        validator: longitude
      - name: latitude
        start: 15
        end: 27
        type: float
        validator: latitude

lookup_tables:
  county_codes:
    '001': Anderson
    '003': Andrews
    '005': Angelina
    '007': Aransas
    '009': Archer
    '011': Armstrong
    '013': Atascosa
    '015': Austin
    '017': Bailey
    '019': Bandera
    '021': Bastrop
    '023': Baylor
    '025': Bee
    '027': Bell
    '029': Bexar
    '031': Blanco
    '033': Borden
    '035': Bosque
    '037': Bowie
    '039': Brazoria
    '041': Brazos
    '043': Brewster
    '045': Briscoe
    '047': Brooks
    '049': Brown
    '051': Burleson
    '053': Burnet
    '055': Caldwell
    '057': Calhoun
    '059': Callahan
    '061': Cameron
    '063': Camp
    '065': Carson
    '067': Cass
    '069': Castro
    '071': Chambers
    '073': Cherokee
    '075': Childress
    '077': Clay
    '079': Cochran
    '081': Coke
    '083': Coleman
    '085': Collin
    '087': Collingsworth
    '089': Colorado
    '091': Comal
    '093': Comanche
    '095': Concho
    '097': Cooke
    '099': Coryell
    '101': Cottle
    '103': Crane
    '105': Crockett
    '107': Crosby
    '109': Culberson
    '111': Dallam
    '113': Dallas
    '115': Dawson
    '117': Deaf Smith
    '119': Delta
    '121': Denton
    '123': DeWitt
    '125': Dickens
    '127': Dimmit
    '129': Donley
    '131': Duval
    '133': Eastland
    '135': Ector
    '137': Edwards
    '139': Ellis
    '141': El Paso
    '143': Erath
    '145': Falls
    '147': Fannin
    '149': Fayette
    '151': Fisher
    '153': Floyd
    '155': Foard
    '157': Fort Bend
    '159': Franklin
    '161': Freestone
    '163': Frio
    '165': Gaines
    '167': Galveston
    '169': Garza
    '171': Gillespie
    '173': Glasscock
    '175': Goliad
    '177': Gonzales
    '179': Gray
    '181': Grayson
    '183': Gregg
    '185': Grimes
    '187': Guadalupe
    '189': Hale
    '191': Hall
    '193': Hamilton
    '195': Hansford
    '197': Hardeman
    '199': Hardin
    '201': Harris
    '203': Harrison
    '205': Hartley
    '207': Haskell
    '209': Hays
    '211': Hemphill
    '213': Henderson
    '215': Hidalgo
    '217': Hill
    '219': Hockley
    '221': Hood
    '223': Hopkins
    '225': Houston
    '227': Howard
    '229': Hudspeth
    '231': Hunt
    '233': Hutchinson
    '235': Irion
    '237': Jack
    '239': Jackson
    '241': Jasper
    '243': Jeff Davis
    '245': Jefferson
    '247': Jim Hogg
    '249': Jim Wells
    '251': Johnson
    '253': Jones
    '255': Karnes
    '257': Kaufman
    '259': Kendall
    '261': Kenedy
    '263': Kent
    '265': Kerr
    '267': Kimble
    '269': King
    '271': Kinney
    '273': Kleberg
    '275': Knox
    '277': Lamar
    '279': Lamb
    '281': Lampasas
    '283': La Salle
    '285': Lavaca
    '287': Lee
    '289': Leon
    '291': Liberty
    '293': Limestone
    '295': Lipscomb
    '297': Live Oak
    '299': Llano
    '301': Loving
    '303': Lubbock
    '305': Lynn
    '307': McCulloch
    '309': McLennan
    '311': McMullen
    '313': Madison
    '315': Marion
    '317': Martin
    '319': Mason
    '321': Matagorda
    '323': Maverick
    '325': Medina
    '327': Menard
    '329': Midland
    '331': Milam
    '333': Mills
    '335': Mitchell
    '337': Montague
    '339': Montgomery
    '341': Moore
    '343': Morris
    '345': Motley
    '347': Nacogdoches
    '349': Navarro
    '351': Newton
    '353': Nolan
    '355': Nueces
    '357': Ochiltree
    '359': Oldham
    '361': Orange
    '363': Palo Pinto
    '365': Panola
    '367': Parker
    '369': Parmer
    '371': Pecos
    '373': Polk
    '375': Potter
    '377': Presidio
    '379': Rains
    '381': Randall
    '383': Reagan
    '385': Real
    '387': Red River
    '389': Reeves
    '391': Refugio
    '393': Roberts
    '395': Robertson
    '397': Rockwall
    '399': Runnels
    '401': Rusk
    '403': Sabine
    '405': San Augustine
    '407': San Jacinto
    '409': San Patricio
    '411': San Saba
    '413': Schleicher
    '415': Scurry
    '417': Shackelford
    '419': Shelby
    '421': Sherman
    '423': Smith
    '425': Somervell
    '427': Starr
    '429': Stephens
    '431': Sterling
    '433': Stonewall
    '435': Sutton
    '437': Swisher
    '439': Tarrant
    '441': Taylor
    '443': Terrell
    '445': Terry
    '447': Throckmorton
    '449': Titus
    '451': Tom Green
    '453': Travis
    '455': Trinity
    '457': Tyler
    '459': Upshur
    '461': Upton
    '463': Uvalde
    '465': Val Verde
    '467': Van Zandt
    '469': Victoria
    '471': Walker
    '473': Waller
    '475': Ward
    '477': Washington
    '479': Webb
    '481': Wharton
    '483': Wheeler
    '485': Wichita
    '487': Wilbarger
    '489': Willacy
    '491': Williamson
    '493': Wilson
    '495': Winkler
    '497': Wise
    '499': Wood
    '501': Yoakum
    '503': Young
    '505': Zapata
    '507': Zavala

validation:
  ranges:
    depth:
      min: 0
      max: 40000
      description: ft
    longitude:
      min: -107.0
      max: -93.0
      description: TX longitude
    latitude:
      min: 25.0
      max: 37.0
      description: TX latitude
  flags:
    valid_values:
      - Y
      - N
      - '0'
      - '9'
      - ' '
  operator_number:
    min_length: 5
    max_length: 6
    numeric_only: true
  district:
    pass: true